/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/historia`; params?: Router.UnknownInputParams; } | { pathname: `/oracao`; params?: Router.UnknownInputParams; } | { pathname: `/campanhas`; params?: Router.UnknownInputParams; } | { pathname: `/aniversariantes`; params?: Router.UnknownInputParams; } | { pathname: `/estudos`; params?: Router.UnknownInputParams; } | { pathname: `/contato`; params?: Router.UnknownInputParams; } | { pathname: `/galeria`; params?: Router.UnknownInputParams; } | { pathname: `/batismo`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/historia`; params?: Router.UnknownOutputParams; } | { pathname: `/oracao`; params?: Router.UnknownOutputParams; } | { pathname: `/campanhas`; params?: Router.UnknownOutputParams; } | { pathname: `/aniversariantes`; params?: Router.UnknownOutputParams; } | { pathname: `/estudos`; params?: Router.UnknownOutputParams; } | { pathname: `/contato`; params?: Router.UnknownOutputParams; } | { pathname: `/galeria`; params?: Router.UnknownOutputParams; } | { pathname: `/batismo`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/historia${`?${string}` | `#${string}` | ''}` | `/oracao${`?${string}` | `#${string}` | ''}` | `/campanhas${`?${string}` | `#${string}` | ''}` | `/aniversariantes${`?${string}` | `#${string}` | ''}` | `/estudos${`?${string}` | `#${string}` | ''}` | `/contato${`?${string}` | `#${string}` | ''}` | `/galeria${`?${string}` | `#${string}` | ''}` | `/batismo${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/historia`; params?: Router.UnknownInputParams; } | { pathname: `/oracao`; params?: Router.UnknownInputParams; } | { pathname: `/campanhas`; params?: Router.UnknownInputParams; } | { pathname: `/aniversariantes`; params?: Router.UnknownInputParams; } | { pathname: `/estudos`; params?: Router.UnknownInputParams; } | { pathname: `/contato`; params?: Router.UnknownInputParams; } | { pathname: `/galeria`; params?: Router.UnknownInputParams; } | { pathname: `/batismo`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
